# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36109436e74c0d8766a100f8862de042ce1ef5303450a364120d9e2f675e60e48504b9c47c02eef0f55a725fbe3c0e43dd4983bdc23fdd160362312c3fe70e93

test:
  secret_key_base: ae7a21d58106878517ee6a1b781d34f8f50d14d5bcfb939f375784cc9d973fec4ef27b009133b9acff2f706b57951086f5445c7fe1400cdd5982d1345be61644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
